# Generated by Django 5.2.7 on 2025-12-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.TextField(null=True)),
                ('e_image', models.ImageField(upload_to='events')),
                ('event_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.event_category')),
            ],
        ),
    ]
