# Generated by Django 5.2.7 on 2026-01-09 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_eventbooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.events'),
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
