# Generated by Django 5.2.7 on 2026-01-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_eventbooking_name_remove_eventbooking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='name',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='name',
            field=models.ManyToManyField(to='app1.events'),
        ),
    ]
