# Generated by Django 5.2.7 on 2026-01-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_eventbooking_name_eventbooking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='name',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.events'),
        ),
    ]
