# Generated by Django 5.2.7 on 2026-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_eventbooking_name_eventbooking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('hoster', 'hoster')], default='user', max_length=50),
        ),
    ]
