# Generated by Django 5.2.7 on 2026-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='admin_approval',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
