# Generated by Django 5.2.7 on 2026-01-20 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_events_admin_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.events')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
