# Generated by Django 5.2.7 on 2026-01-20 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_event_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='hoster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
