# Generated by Django 5.2.7 on 2026-01-21 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_events_hoster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_cancel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.events'),
        ),
    ]
