# Generated by Django 5.2.7 on 2026-01-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_event_cancel_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_cancel',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.events'),
        ),
    ]
