# Generated by Django 5.2.7 on 2026-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admin_approval',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_image',
        ),
        migrations.AddField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
